AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sammy

  Sample SAM Template for Sammy

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.7
    Timeout: 3

Resources:
  GetUsers:
    DependsOn: UsersTable
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/users/get
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        GetUsers:
          Type: Api 
          Properties:
            Path: /users
            Method: get
  PostUser:
    DependsOn: UsersTable
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/users/post
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /users
            Method: post
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
