AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sammy

  Sample SAM Template for Sammy

Globals:
  Function:
    Timeout: 3

Resources:
  GetUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/users/get
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        GetUsers:
          Type: Api 
          Properties:
            Path: /users
            Method: get
  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/users/post
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /users
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
