# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.16

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: validate template
          command: |
            sam validate

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            tox -e py37-unit

      - run:
          name: deploy on stage
          command: |
            sam build 
            sam deploy

      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            tox -e py37-integration

