jobs:
  build:
    executor: aws-serverless/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - aws-serverless/install
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: validate template
          command: |
            sam validate
      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            tox -e py37-unit
      - run:
          name: deploy on stage
          command: |
            sam build 
            sam deploy
      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            export SAMMY_HOST=$(aws cloudformation describe-stacks --stack-name Sammy-stage --query "Stacks[0].Outputs[?OutputKey=='SammyApi'].OutputValue" --output text)
            tox -e py37-integration
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
version: 2.1
workflows:
  validate-code:
    jobs:
      - build
